### ISSUE TITLE
Get the average of the changes in Profit/Losses over the entire period

### ISSUE THREAD

**Issue by sarabenchinoun** [sarabenchinoun/console-finances#3]
### Tasks

- [ ] Track what the total change in profits is from month to month
- [ ] Find the average

**Comment by sarabenchinoun** [comment]
### Tasks

- [ ] Track what the total change in profits is from month to month
- [ ] Find the average
